/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SWING;

/**
 *
 * @author vanes
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContraseñaTextbox = new javax.swing.JPasswordField();
        UsuarioTextbox = new javax.swing.JTextField();
        LoginBTN = new javax.swing.JButton();
        SalirBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContraseñaTextbox.setBackground(new java.awt.Color(255, 249, 235));
        ContraseñaTextbox.setForeground(new java.awt.Color(0, 0, 0));
        ContraseñaTextbox.setText("Contraseña");
        ContraseñaTextbox.setBorder(null);
        ContraseñaTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTextboxActionPerformed(evt);
            }
        });
        getContentPane().add(ContraseñaTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 200, 30));

        UsuarioTextbox.setBackground(new java.awt.Color(255, 249, 235));
        UsuarioTextbox.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 1, 18)); // NOI18N
        UsuarioTextbox.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioTextbox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        UsuarioTextbox.setText("Usuario");
        UsuarioTextbox.setBorder(null);
        UsuarioTextbox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(UsuarioTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 200, 30));

        LoginBTN.setBorder(null);
        LoginBTN.setContentAreaFilled(false);
        LoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTNActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 170, 40));

        SalirBTN.setBorder(null);
        SalirBTN.setContentAreaFilled(false);
        SalirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SalirBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/BG_Login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirBTNActionPerformed

    private void LoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginBTNActionPerformed

    private void ContraseñaTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTextboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ContraseñaTextbox;
    private javax.swing.JButton LoginBTN;
    private javax.swing.JButton SalirBTN;
    private javax.swing.JTextField UsuarioTextbox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
